### ISSUE TITLE
CAD source files for LED Ring and Separator Ring?

### ISSUE THREAD

**Issue by awk** [Dynatrace/ufo#12]
I noticed that the 3dprint folder has the STL files for the LED Ring and Separator Ring, but no CAD source files? It looks like the ufo.123dx files use the LED Ring as an imported STL object (i.e. a mesh)

I'd like to be able to make some tweaks to the LED Ring for my own build and have access to a CAD tool that can handle many formats - do you have an non-mesh model for the rings? In STEP, SAT, or other similar format?

**Comment by flyinggorilla** [comment]
Sorry for my late reply. The 123dx file is the source file. The design was done 100% with Autodesk 123D, so you should be able to modify the ring as non-mesh. You can download Autodesk 123D yourself for free to do modifications. Let me know if you still have troubles. Btw. it would be great if you would share a picture or the like of your ufo version.
