### ISSUE TITLE
multiple errors trying to compile.   

### ISSUE THREAD

**Issue by billieblaze** [Dynatrace/ufo#14]
Trying to compile and getting multiple library related errors.   Would it be possble for you to version control any 3rd party dependencies?   I had to add ArduinoJSON first, and then i started getting errors from ESP libraries..

**Comment by flyinggorilla** [comment]
Hi thanks for the note. I have added the ArduinoJSON library to the howto documentation, which lists the dependencies. For now we wont check-in third parties. We consider moving from ESP8266 to ESP32 and will reconsider how we deal with third party libraries.
